language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest --prefer-stable"
    - PREFER_LOWEST=""

before_script:
  - sed -i 's/"require-dev"/"do-not-install-this"/g' composer.json
  - composer update --no-dev $PREFER_LOWEST

script:
  - mkdir -p build/logs
  - composer require phpunit/phpunit
  - composer require mikey179/vfsStream
  - phpunit --coverage-text  --coverage-clover build/logs/clover.xml

after_script:
  - composer require satooshi/php-coveralls
  - composer require codacy/coverage
  - vendor/bin/coveralls -v
  - vendor/bin/codacycoverage clover build/logs/clover.xml
