dist: trusty

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest --prefer-stable"
    - PREFER_LOWEST=""

before_script:
  - sed -i 's/"require-dev"/"do-not-install-this"/g' composer.json
  - composer update --no-dev $PREFER_LOWEST

script:
  - mkdir -p build/logs
  - composer require phpunit/phpunit:"<8"
  - composer require mikey179/vfsstream
  - vendor/bin/phpunit --coverage-text  --coverage-clover build/logs/clover.xml

after_script:
  - composer require php-coveralls/php-coveralls
  - composer require codacy/coverage
  - vendor/bin/php-coveralls -v
  - vendor/bin/codacycoverage clover build/logs/clover.xml

notifications:
  email: false
